;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        org-delete-char
        org-force-self-insert
        org-self-insert-command
        orgtbl-self-insert-command
        paredit-forward-delete
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        ))
