;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        easy-kill
        end-of-visual-line
        go-mode-insert-and-indent
        kill-region
        org-delete-char
        org-force-self-insert
        org-self-insert-command
        orgtbl-self-insert-command
        paredit-forward-delete
        prelude-move-beginning-of-line
        prelude-top-join-line
        ruby-tools-interpolate
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-splice-sexp-killing-backward
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        eshell-previous-matching-input-from-input
        helm-M-x
        ns-handle-scroll-bar-event
        pop-global-mark
        smex
        undo-tree-visualize
        wgrep-finish-edit
        yas-expand
        ))
