;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        org-delete-char
        org-force-self-insert
        org-self-insert-command
        orgtbl-self-insert-command
        paredit-forward-delete
        ruby-tools-interpolate
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-word
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        smex
        ))
