;;; Uncomment the modules you'd like to use and restart Prelude afterwards

(require 'prelude-org)
(require 'prelude-c)
(require 'prelude-clojure)
(require 'prelude-coffee)
;;(require 'prelude-company)
(require 'prelude-css)
(require 'prelude-elixir)
(require 'prelude-emacs-lisp)
(require 'prelude-erc)
;;(require 'prelude-evil)
(require 'prelude-helm)
(require 'prelude-helm-everywhere)
;;(require 'prelude-ido)
(require 'prelude-js)
(require 'prelude-lisp)
(require 'prelude-perl)
(require 'prelude-programming)
(require 'prelude-ruby)
(require 'prelude-scheme)
(require 'prelude-scss)
(require 'prelude-shell)
(require 'prelude-web)
(require 'prelude-xml)
(require 'prelude-yaml)

;; (require 'prelude-common-lisp)
;; (require 'prelude-erlang)
;; (require 'prelude-go) seems broken because of projectile-go
;; (require 'prelude-key-chord)
;; (require 'prelude-latex)
;; (require 'prelude-mediawiki)
;; (require 'prelude-python)
;; (require 'prelude-scala)
